### PR TITLE
Added optional parameter to ago to allow short output

### PR DESCRIPTION
**Pull request by Limero**
Example of output with parameter set:
ta.ago(new Date()-1000, true);  =>  "1s"
ta.ago(new Date()-1000 * 60, true); => "1m"
ta.ago(new Date()-1000 * 60 * 60, true); => "1h"

### CODE REVIEW

**Comment by Limero** [comment]
@digplan Is this feature something that your are interested in merging, or should I put my fork up separately on NPM?

**Comment by digplan** [comment]
Thanks!

**Comment by Limero** [comment]
Please put the latest release on NPM as well. Thank you!

**Comment by andypmw** [comment]
It seems latest release is not at NPM yet, right?

**Pull request merged**
